# shell_smart_pay_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellSmartPayApi
  # CollectingCompany Model.
  class CollectingCompany < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The ID of the Collecting Company (in GFN), also known as Shell Code of the
    # selected payer. This property is mandatory if the ColCoCode code is not
    # passed
    # @return [String]
    attr_accessor :col_co_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['col_co_id'] = 'ColCoId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(col_co_id = nil)
      @col_co_id = col_co_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      col_co_id = hash.key?('ColCoId') ? hash['ColCoId'] : nil

      # Create object from extracted values.
      CollectingCompany.new(col_co_id)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} col_co_id: #{@col_co_id}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} col_co_id: #{@col_co_id.inspect}>"
    end
  end
end
