# shell_smart_pay_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellSmartPayApi
  # PaymentEnablementResponse Model.
  class PaymentEnablementResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # DPan Last number
    # @return [String]
    attr_accessor :dpan_last4

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['dpan_last4'] = 'dpanLast4'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(dpan_last4 = nil)
      @dpan_last4 = dpan_last4
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      dpan_last4 = hash.key?('dpanLast4') ? hash['dpanLast4'] : nil

      # Create object from extracted values.
      PaymentEnablementResponse.new(dpan_last4)
    end

    # Provides a human-readable string representation of the object.
    def to_s
      class_name = self.class.name.split('::').last
      "<#{class_name} dpan_last4: #{@dpan_last4}>"
    end

    # Provides a debugging-friendly string with detailed object information.
    def inspect
      class_name = self.class.name.split('::').last
      "<#{class_name} dpan_last4: #{@dpan_last4.inspect}>"
    end
  end
end
