# shell_smart_pay_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellSmartPayApi
  # type.
  class TypeEnum
    TYPE_ENUM = [
      # TODO: Write general description for ENUM_0
      ENUM_0 = 0,

      # TODO: Write general description for ENUM_1
      ENUM_1 = 1,

      # TODO: Write general description for ENUM_2
      ENUM_2 = 2,

      # TODO: Write general description for ENUM_3
      ENUM_3 = 3
    ].freeze

    def self.validate(value)
      return false if value.nil?

      TYPE_ENUM.include?(value)
    end
  end
end
