# shell_smart_pay_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellSmartPayApi
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
