# shell_smart_pay_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellSmartPayApi
  # HTTP Methods Enumeration.
  class HttpMethodEnum < CoreLibrary::HttpMethod
  end
end
