# shell_smart_pay_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellSmartPayApi
  # Http response received.
  class HttpResponse < CoreLibrary::HttpResponse
  end
end
