# shell_smart_pay_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellSmartPayApi
  # HttpCallBack allows defining callables for pre and post API calls.
  class HttpCallBack < CoreLibrary::HttpCallback
  end
end
