# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class ShellAPIPlatformSecurityAuthenticationControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    setup_class
    @controller = @client.shell_api_platform_security_authentication
    @response_catcher = @controller.http_call_back
  end

  # To obtain APIGEE access token
  def test_oauth_token_post
    # Parameters for the API call
    grant_type = 'client_credentials'
    client_id = 'SOFflRakNlwnWlxfOXQ4GHDVyqGawuKA'
    client_secret = 'cRnWgw7gACqM3gVS'

    # Perform the API call through the SDK function
    result = @controller.oauth_token_post(grant_type, client_id, client_secret)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

end