# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class StationLocatorControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    setup_class
    @controller = @client.station_locator
    @response_catcher = @controller.http_call_back
  end

  # Returns all sites within specified radius of specified GPS location. Sites of all Types are returned. This call must be used when attempting to establish the station the user is located at as part of fuelling journey (i.e. user has to be within 300m of station to be considered located at the station). This API could also be used as a general query to find nearby Shell locations
  def test_stationlocator_v1_stations_get_around_location
    # Parameters for the API call
    m = 'aroundLocation'
    lon = 77.6730103
    lat = 12.9132169
    radius = 0.3
    offer_code = nil
    n = nil
    amenities = nil
    countries = nil

    # Perform the API call through the SDK function
    result = @controller.stationlocator_v1_stations_get_around_location(
      m, lon, lat, radius, offer_code: offer_code, n: n, amenities: amenities,
      countries: countries
    )

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

end