# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class PartnerNotificationControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    setup_class
    @controller = @client.partner_notification
    @response_catcher = @controller.http_call_back
  end

  # To access the Partner’s endpoints, for sending callback messages, Shell will need to connect to the Partner API end points. It is recemmended that the partner offers OAuth 2.0 as a standard for call back APIs and will require the OAuth 2.0 token for authentication. Note this needs to be implemented over HTTPS
  def test_partner_token
    # Parameters for the API call
    grant_type = 'client_credentials'
    client_id = 'SOFflRakNlwnWlxfOXQ4GHDVyqGawuKA'
    client_secret = 'cRnWgw7gACqM3gVS'

    # Perform the API call through the SDK function
    result = @controller.partner_token(grant_type, client_id, client_secret)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))
  end

  # Enables Shell to inform partner of the successful completion of a transaction. Note this needs to be implemented over HTTPS
  def test_finalise_fueling
    # Parameters for the API call
    body = nil

    # Perform the API call through the SDK function
    @controller.finalise_fueling(body: body)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
  end

  # Enables Shell to inform partner that a Mobile Payment transaction has been cancelled by Shell as an error/issue occured. Note this needs to be implemented over HTTPS
  def test_cancel_fueling
    # Parameters for the API call
    body = nil

    # Perform the API call through the SDK function
    @controller.cancel_fueling(body: body)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)
  end

end