# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # CancelFuelingRequest Model.
  class CancelFuelingRequest < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :mpp_transaction_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :reason_code

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['mpp_transaction_id'] = 'mppTransactionId'
      @_hash['reason_code'] = 'reasonCode'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        mpp_transaction_id
        reason_code
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(mpp_transaction_id = SKIP,
                   reason_code = SKIP)
      @mpp_transaction_id = mpp_transaction_id unless mpp_transaction_id == SKIP
      @reason_code = reason_code unless reason_code == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      mpp_transaction_id =
        hash.key?('mppTransactionId') ? hash['mppTransactionId'] : SKIP
      reason_code = hash.key?('reasonCode') ? hash['reasonCode'] : SKIP

      # Create object from extracted values.
      CancelFuelingRequest.new(mpp_transaction_id,
                               reason_code)
    end
  end
end
