# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # An error response.
  class FaultResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [FaultResponseFault]
    attr_accessor :fault

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['fault'] = 'fault'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        fault
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(fault = SKIP)
      @fault = fault unless fault == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      fault = FaultResponseFault.from_hash(hash['fault']) if hash['fault']

      # Create object from extracted values.
      FaultResponse.new(fault)
    end
  end
end
