# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # FinaliseFuelingRequestProductsItems Model.
  class FinaliseFuelingRequestProductsItems < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :product_id

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :product_name

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :unit_price

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['product_id'] = 'productId'
      @_hash['product_name'] = 'productName'
      @_hash['unit_price'] = 'unitPrice'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        product_id
        product_name
        unit_price
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(product_id = SKIP,
                   product_name = SKIP,
                   unit_price = SKIP)
      @product_id = product_id unless product_id == SKIP
      @product_name = product_name unless product_name == SKIP
      @unit_price = unit_price unless unit_price == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      product_id = hash.key?('productId') ? hash['productId'] : SKIP
      product_name = hash.key?('productName') ? hash['productName'] : SKIP
      unit_price = hash.key?('unitPrice') ? hash['unitPrice'] : SKIP

      # Create object from extracted values.
      FinaliseFuelingRequestProductsItems.new(product_id,
                                              product_name,
                                              unit_price)
    end
  end
end
