# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # LoyaltyDetails Model.
  class LoyaltyDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The user’s Loyalty card number. Although this is optional the expectation
    # is that if this is specified then loyaltyType must also be specified
    # @return [String]
    attr_accessor :loyalty_id

    # Loyalty type being used, associated to the loyalty ID being passed.
    # Possible values are 'Shell'
    # @return [String]
    attr_accessor :loyalty_type

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['loyalty_id'] = 'loyaltyId'
      @_hash['loyalty_type'] = 'loyaltyType'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(loyalty_id = nil,
                   loyalty_type = nil)
      @loyalty_id = loyalty_id
      @loyalty_type = loyalty_type
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      loyalty_id = hash.key?('loyaltyId') ? hash['loyaltyId'] : nil
      loyalty_type = hash.key?('loyaltyType') ? hash['loyaltyType'] : nil

      # Create object from extracted values.
      LoyaltyDetails.new(loyalty_id,
                         loyalty_type)
    end
  end
end
