# shell_ev
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellEv
  # Utility class for custom header authorization.
  class MppToken < CoreLibrary::HeaderAuth
    # Display error message on occurrence of authentication failure.
    # @returns [String] The oAuth error message.
    def error_message
      'MppToken: authorization is undefined.'
    end

    # Initialization constructor.
    def initialize(mpp_token_credentials)
      auth_params = {}
      auth_params['Authorization'] = mpp_token_credentials.authorization unless
        mpp_token_credentials.nil? || mpp_token_credentials.authorization.nil?

      super auth_params
    end
  end

  # Data class for MppTokenCredentials.
  # Data class for MppTokenCredentials.
  class MppTokenCredentials
    attr_reader :authorization

    def initialize(authorization:)
      raise ArgumentError, 'authorization cannot be nil' if authorization.nil?

      @authorization = authorization
    end

    def clone_with(authorization: nil)
      authorization ||= self.authorization

      MppTokenCredentials.new(authorization: authorization)
    end
  end
end
