# shell_smart_pay_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ShellSmartPayApi
  # Utility class for custom header authorization.
  class OAuthTokenPost < CoreLibrary::HeaderAuth
    # Display error message on occurrence of authentication failure.
    # @returns [String] The oAuth error message.
    def error_message
      'OAuthTokenPost: x_apigee_authorization is undefined.'
    end

    # Initialization constructor.
    def initialize(o_auth_token_post_credentials)
      auth_params = {}
      auth_params['X-Apigee-Authorization'] = o_auth_token_post_credentials.x_apigee_authorization unless
        o_auth_token_post_credentials.nil? || o_auth_token_post_credentials.x_apigee_authorization.nil?

      super auth_params
    end
  end

  # Data class for OAuthTokenPostCredentials.
  # Data class for OAuthTokenPostCredentials.
  class OAuthTokenPostCredentials
    attr_reader :x_apigee_authorization

    def initialize(x_apigee_authorization:)
      raise ArgumentError, 'x_apigee_authorization cannot be nil' if x_apigee_authorization.nil?

      @x_apigee_authorization = x_apigee_authorization
    end

    def clone_with(x_apigee_authorization: nil)
      x_apigee_authorization ||= self.x_apigee_authorization

      OAuthTokenPostCredentials.new(
        x_apigee_authorization: x_apigee_authorization
      )
    end
  end
end
